# Generated by Django 4.2.6 on 2023-12-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonnik', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='foto',
        ),
        migrations.AddField(
            model_name='dream',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/', verbose_name='Фото'),
        ),
    ]
