# Generated by Django 4.2.6 on 2024-02-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklavkacategory',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
