# Generated by Django 4.2.6 on 2024-01-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arkan',
            old_name='foto',
            new_name='photo',
        ),
    ]
